name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'
      prerelease:
        description: 'Mark as prerelease'
        required: false
        type: boolean
        default: false

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
    
    - name: Create agent package
      run: |
        mkdir -p agent-package
        cp agent/update-config.php agent-package/
        cp README.md agent-package/
        
        # 创建安装脚本
        cat > agent-package/install.sh << 'EOF'
        #!/bin/bash
        set -e
        
        echo "Installing Sing-box Config Agent..."
        
        # 检查root权限
        if [[ $EUID -ne 0 ]]; then
           echo "This script must be run as root" 
           exit 1
        fi
        
        # 创建目录
        mkdir -p /opt/sing-box-agent
        mkdir -p /var/log
        
        # 复制文件
        cp update-config.php /opt/sing-box-agent/
        
        # 设置权限
        chmod +x /opt/sing-box-agent/update-config.php
        
        # 创建systemd服务
        cat > /etc/systemd/system/sing-box-agent.service << 'SERVICE'
        [Unit]
        Description=Sing-box Config Agent
        After=network.target
        
        [Service]
        Type=oneshot
        RemainAfterExit=yes
        ExecStart=/bin/true
        
        [Install]
        WantedBy=multi-user.target
        SERVICE
        
        # 创建nginx配置示例
        cat > /etc/nginx/sites-available/sing-box-agent << 'NGINX'
        server {
            listen 80;
            server_name your-domain.com;
            
            location /update-config {
                if ($request_method != POST) {
                    return 405;
                }
                
                include fastcgi_params;
                fastcgi_pass unix:/var/run/php/php8.2-fpm.sock;
                fastcgi_param SCRIPT_FILENAME /opt/sing-box-agent/update-config.php;
            }
        }
        NGINX
        
        echo "Installation complete!"
        echo "1. Edit /opt/sing-box-agent/update-config.php to set your token"
        echo "2. Configure nginx: ln -s /etc/nginx/sites-available/sing-box-agent /etc/nginx/sites-enabled/"
        echo "3. Restart nginx: systemctl restart nginx"
        echo "4. Test: curl -X POST -d 'token=YOUR_TOKEN&config={}' http://your-domain.com/update-config"
        EOF
        
        chmod +x agent-package/install.sh
        
        # 创建压缩包
        tar -czf "sing-box-agent-${{ github.event.inputs.version }}.tar.gz" -C agent-package .
    
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: sing-box-agent-${{ github.event.inputs.version }}.tar.gz
        name: Release ${{ github.event.inputs.version }}
        tag_name: ${{ github.event.inputs.version }}
        prerelease: ${{ github.event.inputs.prerelease }}
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
